site_name: process-bigraph-lang
repo_url: https://github.com/biosimulations/process-bigraph-lang
site_url: https://biosimulations.github.io/process-bigraph-lang
site_description: This is a LSP, CLI and Python package for a domain specific language for process bigraphs.
site_author: Jim Schaff
edit_uri: edit/main/docs/
repo_name: biosimulations/process-bigraph-lang
copyright: Maintained by <a href="https://biosimulations.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biosimulations/process-bigraph-lang
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/process-bigraph-lang

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
