name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.11"

runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - uses: abatilo/actions-poetry@v3

    - name: Configure Poetry virtual environment in project
      run: poetry config virtualenvs.in-project true
      shell: bash

    - name: Setup Node.js v23
      uses: actions/setup-node@v4
      with:
        node-version: 23

    - name: Install python dependencies
      run: poetry install --no-interaction
      shell: bash

    - name: build project and wheels to install the DSL CLI executable needed for pytest)
      run: poetry build --no-interaction
      shell: bash
